{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "feab.fullname" .}}
  namespace: {{ .Values.image.namespace }}
  labels:
    app: {{ template "feab.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "feab.serviceAccountName" .}}
    namespace: {{ .Values.image.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "feab.fullname" .}}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
