{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "feab.fullname" .}}
  namespace: {{ .Values.image.namespace }}
  labels:
    app: {{ template "feab.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups:
      - extensions
      - ""
    resources:
      - namespaces
      - pods
      - replicationcontrollers
      - services
      - events
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
{{- if .Values.podSecurityPolicy.create }}
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ template "feab.fullname" . }}
    verbs:
      - use
{{- end }}
{{- end }}
